version: '3.9'

services:
  web:
    build: ./frontend
    ports:
      - "443:443"
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/backend
  db:
    image: postgres:15.2
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: backend

volumes:
  postgres-data: