FROM ruby:3.0.2

WORKDIR /app

RUN apk update && \
    apk add --no-cache \
    build-base \
    postgresql-dev \
    nodejs \
    yarn

COPY Gemfile Gemfile.lock ./

RUN bundle install --jobs $(nproc) --no-cache

COPY . .

CMD ["rails", "server", "-b", "0.0.0.0"]